theme: minima
title: Working Title
author: n00bstermj
email: donttakemysandwich@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello. I like writing and reading and consuming content.
  I'm exploring Github and hope to be an excellent programmer.
  
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: BarackObama # DO NOT include the @ character, or else the build will fail!
github_username:  andrew # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
